  name: 功能请求 / Feature Request
  description: 提交一个功能请求 / Create a feature request
  labels:
    - "feature"
  body:
    - type: markdown
      attributes:
          value: |
            感谢您愿意为 FEhViewer 做出贡献！
            提交功能请求前，还请首先完成文末的自查步骤
    
            Thanks for your contribution to the FEhViewer Project!
            Please complete the self-review steps at the end of the article before submitting the feature request

    - type: textarea
      id: reproduce
      attributes:
        label: 功能描述 / Feature description
        description: |
          在此处写下希望添加的功能
          Describe the feature here
        placeholder: |
          它应该 ...
          It should be ...
      validations:
        required: true

    - type: textarea
      id: more
      attributes:
        label: 备注 / Additional details
        description: |
          在此处写下其他您想说的内容
          Describe additional details here
        placeholder: |
          其他有用的信息与附件
          Additional details and attachments
      validations:
        required: false

    - type: checkboxes
      id: check
      attributes:
        label: 自查步骤 / Self-review steps
        description: |
          请确保您已经遵守以下所有必选项，否则 issue 会被立即关闭
          Please ensure you have obtained all needed options, otherwise the issue will be closed immediately
        options:
          - label: 如果您有足够的时间和能力，并愿意为此功能请求提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
            required: false

          - label: 您已搜索过 [Issue Tracker](https://github.com/3003h/FEhViewer/issues)，没有找到类似的请求 / I have searched on [Issue Tracker](https://github.com/3003h/FEhViewer/issues), No duplicate or related open issue has been found
            required: true

          - label: 您确保这个 Issue 只发起一个功能请求。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
            required: true