import 'package:flutter/foundation.dart';
import 'eh_profile.dart';
import 'eh_setting_item.dart';
import 'eh_setting_item.dart';

@immutable
class EhSettings {
  
  const EhSettings({
    required this.profilelist,
    this.profileSelected,
    this.defaultProfile,
    this.loadImageThroughHAtH,
    this.loadBrowsingCountry,
    this.imageSize,
    this.imageSizeHorizontal,
    this.imageSizeVertical,
    this.galleryNameDisplay,
    this.archiverSettings,
    this.frontPageSettings,
    this.ctDoujinshi,
    this.ctManga,
    this.ctArtistcg,
    this.ctGamecg,
    this.ctWestern,
    this.ctNonH,
    this.ctImageset,
    this.ctCosplay,
    this.ctAsianporn,
    this.ctMisc,
    this.favorites0,
    this.favorites1,
    this.favorites2,
    this.favorites3,
    this.favorites4,
    this.favorites5,
    this.favorites6,
    this.favorites7,
    this.favorites8,
    this.favorites9,
    this.sortOrderFavorites,
    this.ratings,
    required this.xn,
    required this.xl,
    this.xlJpnTl1024,
    this.xlJpnRw2048,
    this.xlEnOr1,
    this.xlEnTr1025,
    this.xlEnRe2049,
    this.xlChiOr10,
    this.xlChiTr1034,
    this.xlChiRe2058,
    this.xlDutOr20,
    this.xlDutTr1044,
    this.xlDutRe2068,
    this.xlFrOr30,
    this.xlFrTr1054,
    this.xlFrRe2078,
    this.xlGmOr40,
    this.xlGmTr1064,
    this.xlGmRe2088,
    this.xlHungOr50,
    this.xlHungTr1074,
    this.xlHungRe2098,
    this.xlItaOr60,
    this.xlItaTr1084,
    this.xlItaRe2108,
    this.xlKrOr70,
    this.xlKrTr1094,
    this.xlKrRe2118,
    this.xlPoliOr80,
    this.xlPoliTr1104,
    this.xlPoliRe2128,
    this.xlPorOr90,
    this.xlPorTr1114,
    this.xlPorRe2138,
    this.xlRuOr100,
    this.xlRuTr1124,
    this.xlRuRe2148,
    this.xlSpaOr110,
    this.xlSpaTr1134,
    this.xlSpaRe2158,
    this.xlThaiOr120,
    this.xlThaiTr1144,
    this.xlThaiRe2168,
    this.xlVieOr130,
    this.xlVieTr1154,
    this.xlVieRe2178,
    this.xlNaOr254,
    this.xlNaTr1278,
    this.xlNaRe2302,
    this.xlOthOr255,
    this.xlOthTr1279,
    this.xlOthRe2303,
    this.tagFilteringThreshold,
    this.tagWatchingThreshold,
    this.excludedLanguages,
    this.excludedUploaders,
    this.searchResultCount,
    this.mouseOverThumbnails,
    this.thumbnailSize,
    this.thumbnailRows,
    this.thumbnailScaling,
    this.viewportOverride,
    this.sortOrderComments,
    this.showCommentVotes,
    this.sortOrderTags,
    this.showGalleryPageNumbers,
    this.hentaiAtHomeLocalNetworkHost,
    this.originalImages,
    this.alwaysUseMpv,
    this.mpvStyle,
    this.mpvThumbnailPane,
  });

  final List<EhProfile> profilelist;
  final String? profileSelected;
  final String? defaultProfile;
  final String? loadImageThroughHAtH;
  final String? loadBrowsingCountry;
  final String? imageSize;
  final String? imageSizeHorizontal;
  final String? imageSizeVertical;
  final String? galleryNameDisplay;
  final String? archiverSettings;
  final String? frontPageSettings;
  final String? ctDoujinshi;
  final String? ctManga;
  final String? ctArtistcg;
  final String? ctGamecg;
  final String? ctWestern;
  final String? ctNonH;
  final String? ctImageset;
  final String? ctCosplay;
  final String? ctAsianporn;
  final String? ctMisc;
  final String? favorites0;
  final String? favorites1;
  final String? favorites2;
  final String? favorites3;
  final String? favorites4;
  final String? favorites5;
  final String? favorites6;
  final String? favorites7;
  final String? favorites8;
  final String? favorites9;
  final String? sortOrderFavorites;
  final String? ratings;
  final List<EhSettingItem> xn;
  final List<EhSettingItem> xl;
  final String? xlJpnTl1024;
  final String? xlJpnRw2048;
  final String? xlEnOr1;
  final String? xlEnTr1025;
  final String? xlEnRe2049;
  final String? xlChiOr10;
  final String? xlChiTr1034;
  final String? xlChiRe2058;
  final String? xlDutOr20;
  final String? xlDutTr1044;
  final String? xlDutRe2068;
  final String? xlFrOr30;
  final String? xlFrTr1054;
  final String? xlFrRe2078;
  final String? xlGmOr40;
  final String? xlGmTr1064;
  final String? xlGmRe2088;
  final String? xlHungOr50;
  final String? xlHungTr1074;
  final String? xlHungRe2098;
  final String? xlItaOr60;
  final String? xlItaTr1084;
  final String? xlItaRe2108;
  final String? xlKrOr70;
  final String? xlKrTr1094;
  final String? xlKrRe2118;
  final String? xlPoliOr80;
  final String? xlPoliTr1104;
  final String? xlPoliRe2128;
  final String? xlPorOr90;
  final String? xlPorTr1114;
  final String? xlPorRe2138;
  final String? xlRuOr100;
  final String? xlRuTr1124;
  final String? xlRuRe2148;
  final String? xlSpaOr110;
  final String? xlSpaTr1134;
  final String? xlSpaRe2158;
  final String? xlThaiOr120;
  final String? xlThaiTr1144;
  final String? xlThaiRe2168;
  final String? xlVieOr130;
  final String? xlVieTr1154;
  final String? xlVieRe2178;
  final String? xlNaOr254;
  final String? xlNaTr1278;
  final String? xlNaRe2302;
  final String? xlOthOr255;
  final String? xlOthTr1279;
  final String? xlOthRe2303;
  final String? tagFilteringThreshold;
  final String? tagWatchingThreshold;
  final String? excludedLanguages;
  final String? excludedUploaders;
  final String? searchResultCount;
  final String? mouseOverThumbnails;
  final String? thumbnailSize;
  final String? thumbnailRows;
  final String? thumbnailScaling;
  final String? viewportOverride;
  final String? sortOrderComments;
  final String? showCommentVotes;
  final String? sortOrderTags;
  final String? showGalleryPageNumbers;
  final String? hentaiAtHomeLocalNetworkHost;
  final String? originalImages;
  final String? alwaysUseMpv;
  final String? mpvStyle;
  final String? mpvThumbnailPane;

  factory EhSettings.fromJson(Map<String,dynamic> json) => EhSettings(
    profilelist: (json['profilelist'] as List? ?? []).map((e) => EhProfile.fromJson(e as Map<String, dynamic>)).toList(),
    profileSelected: json['profile_selected'] != null ? json['profile_selected'] as String : null,
    defaultProfile: json['default_profile'] != null ? json['default_profile'] as String : null,
    loadImageThroughHAtH: json['load_image_through_hAtH'] != null ? json['load_image_through_hAtH'] as String : null,
    loadBrowsingCountry: json['load_browsing_country'] != null ? json['load_browsing_country'] as String : null,
    imageSize: json['image_size'] != null ? json['image_size'] as String : null,
    imageSizeHorizontal: json['image_size_horizontal'] != null ? json['image_size_horizontal'] as String : null,
    imageSizeVertical: json['image_size_vertical'] != null ? json['image_size_vertical'] as String : null,
    galleryNameDisplay: json['gallery_name_display'] != null ? json['gallery_name_display'] as String : null,
    archiverSettings: json['archiver_settings'] != null ? json['archiver_settings'] as String : null,
    frontPageSettings: json['front_page_settings'] != null ? json['front_page_settings'] as String : null,
    ctDoujinshi: json['ct_doujinshi'] != null ? json['ct_doujinshi'] as String : null,
    ctManga: json['ct_manga'] != null ? json['ct_manga'] as String : null,
    ctArtistcg: json['ct_artistcg'] != null ? json['ct_artistcg'] as String : null,
    ctGamecg: json['ct_gamecg'] != null ? json['ct_gamecg'] as String : null,
    ctWestern: json['ct_western'] != null ? json['ct_western'] as String : null,
    ctNonH: json['ct_non-h'] != null ? json['ct_non-h'] as String : null,
    ctImageset: json['ct_imageset'] != null ? json['ct_imageset'] as String : null,
    ctCosplay: json['ct_cosplay'] != null ? json['ct_cosplay'] as String : null,
    ctAsianporn: json['ct_asianporn'] != null ? json['ct_asianporn'] as String : null,
    ctMisc: json['ct_misc'] != null ? json['ct_misc'] as String : null,
    favorites0: json['favorites0'] != null ? json['favorites0'] as String : null,
    favorites1: json['favorites1'] != null ? json['favorites1'] as String : null,
    favorites2: json['favorites2'] != null ? json['favorites2'] as String : null,
    favorites3: json['favorites3'] != null ? json['favorites3'] as String : null,
    favorites4: json['favorites4'] != null ? json['favorites4'] as String : null,
    favorites5: json['favorites5'] != null ? json['favorites5'] as String : null,
    favorites6: json['favorites6'] != null ? json['favorites6'] as String : null,
    favorites7: json['favorites7'] != null ? json['favorites7'] as String : null,
    favorites8: json['favorites8'] != null ? json['favorites8'] as String : null,
    favorites9: json['favorites9'] != null ? json['favorites9'] as String : null,
    sortOrderFavorites: json['sort_order_favorites'] != null ? json['sort_order_favorites'] as String : null,
    ratings: json['ratings'] != null ? json['ratings'] as String : null,
    xn: (json['xn'] as List? ?? []).map((e) => EhSettingItem.fromJson(e as Map<String, dynamic>)).toList(),
    xl: (json['xl'] as List? ?? []).map((e) => EhSettingItem.fromJson(e as Map<String, dynamic>)).toList(),
    xlJpnTl1024: json['xl_jpn_tl_1024'] != null ? json['xl_jpn_tl_1024'] as String : null,
    xlJpnRw2048: json['xl_jpn_rw_2048'] != null ? json['xl_jpn_rw_2048'] as String : null,
    xlEnOr1: json['xl_en_or_1'] != null ? json['xl_en_or_1'] as String : null,
    xlEnTr1025: json['xl_en_tr_1025'] != null ? json['xl_en_tr_1025'] as String : null,
    xlEnRe2049: json['xl_en_re_2049'] != null ? json['xl_en_re_2049'] as String : null,
    xlChiOr10: json['xl_chi_or_10'] != null ? json['xl_chi_or_10'] as String : null,
    xlChiTr1034: json['xl_chi_tr_1034'] != null ? json['xl_chi_tr_1034'] as String : null,
    xlChiRe2058: json['xl_chi_re_2058'] != null ? json['xl_chi_re_2058'] as String : null,
    xlDutOr20: json['xl_dut_or_20'] != null ? json['xl_dut_or_20'] as String : null,
    xlDutTr1044: json['xl_dut_tr_1044'] != null ? json['xl_dut_tr_1044'] as String : null,
    xlDutRe2068: json['xl_dut_re_2068'] != null ? json['xl_dut_re_2068'] as String : null,
    xlFrOr30: json['xl_fr_or_30'] != null ? json['xl_fr_or_30'] as String : null,
    xlFrTr1054: json['xl_fr_tr_1054'] != null ? json['xl_fr_tr_1054'] as String : null,
    xlFrRe2078: json['xl_fr_re_2078'] != null ? json['xl_fr_re_2078'] as String : null,
    xlGmOr40: json['xl_gm_or_40'] != null ? json['xl_gm_or_40'] as String : null,
    xlGmTr1064: json['xl_gm_tr_1064'] != null ? json['xl_gm_tr_1064'] as String : null,
    xlGmRe2088: json['xl_gm_re_2088'] != null ? json['xl_gm_re_2088'] as String : null,
    xlHungOr50: json['xl_hung_or_50'] != null ? json['xl_hung_or_50'] as String : null,
    xlHungTr1074: json['xl_hung_tr_1074'] != null ? json['xl_hung_tr_1074'] as String : null,
    xlHungRe2098: json['xl_hung_re_2098'] != null ? json['xl_hung_re_2098'] as String : null,
    xlItaOr60: json['xl_ita_or_60'] != null ? json['xl_ita_or_60'] as String : null,
    xlItaTr1084: json['xl_ita_tr_1084'] != null ? json['xl_ita_tr_1084'] as String : null,
    xlItaRe2108: json['xl_ita_re_2108'] != null ? json['xl_ita_re_2108'] as String : null,
    xlKrOr70: json['xl_kr_or_70'] != null ? json['xl_kr_or_70'] as String : null,
    xlKrTr1094: json['xl_kr_tr_1094'] != null ? json['xl_kr_tr_1094'] as String : null,
    xlKrRe2118: json['xl_kr_re_2118'] != null ? json['xl_kr_re_2118'] as String : null,
    xlPoliOr80: json['xl_poli_or_80'] != null ? json['xl_poli_or_80'] as String : null,
    xlPoliTr1104: json['xl_poli_tr_1104'] != null ? json['xl_poli_tr_1104'] as String : null,
    xlPoliRe2128: json['xl_poli_re_2128'] != null ? json['xl_poli_re_2128'] as String : null,
    xlPorOr90: json['xl_por_or_90'] != null ? json['xl_por_or_90'] as String : null,
    xlPorTr1114: json['xl_por_tr_1114'] != null ? json['xl_por_tr_1114'] as String : null,
    xlPorRe2138: json['xl_por_re_2138'] != null ? json['xl_por_re_2138'] as String : null,
    xlRuOr100: json['xl_ru_or_100'] != null ? json['xl_ru_or_100'] as String : null,
    xlRuTr1124: json['xl_ru_tr_1124'] != null ? json['xl_ru_tr_1124'] as String : null,
    xlRuRe2148: json['xl_ru_re_2148'] != null ? json['xl_ru_re_2148'] as String : null,
    xlSpaOr110: json['xl_spa_or_110'] != null ? json['xl_spa_or_110'] as String : null,
    xlSpaTr1134: json['xl_spa_tr_1134'] != null ? json['xl_spa_tr_1134'] as String : null,
    xlSpaRe2158: json['xl_spa_re_2158'] != null ? json['xl_spa_re_2158'] as String : null,
    xlThaiOr120: json['xl_thai_or_120'] != null ? json['xl_thai_or_120'] as String : null,
    xlThaiTr1144: json['xl_thai_tr_1144'] != null ? json['xl_thai_tr_1144'] as String : null,
    xlThaiRe2168: json['xl_thai_re_2168'] != null ? json['xl_thai_re_2168'] as String : null,
    xlVieOr130: json['xl_vie_or_130'] != null ? json['xl_vie_or_130'] as String : null,
    xlVieTr1154: json['xl_vie_tr_1154'] != null ? json['xl_vie_tr_1154'] as String : null,
    xlVieRe2178: json['xl_vie_re_2178'] != null ? json['xl_vie_re_2178'] as String : null,
    xlNaOr254: json['xl_na_or_254'] != null ? json['xl_na_or_254'] as String : null,
    xlNaTr1278: json['xl_na_tr_1278'] != null ? json['xl_na_tr_1278'] as String : null,
    xlNaRe2302: json['xl_na_re_2302'] != null ? json['xl_na_re_2302'] as String : null,
    xlOthOr255: json['xl_oth_or_255'] != null ? json['xl_oth_or_255'] as String : null,
    xlOthTr1279: json['xl_oth_tr_1279'] != null ? json['xl_oth_tr_1279'] as String : null,
    xlOthRe2303: json['xl_oth_re_2303'] != null ? json['xl_oth_re_2303'] as String : null,
    tagFilteringThreshold: json['tag_filtering_threshold'] != null ? json['tag_filtering_threshold'] as String : null,
    tagWatchingThreshold: json['tag_watching_threshold'] != null ? json['tag_watching_threshold'] as String : null,
    excludedLanguages: json['excluded_languages'] != null ? json['excluded_languages'] as String : null,
    excludedUploaders: json['excluded_uploaders'] != null ? json['excluded_uploaders'] as String : null,
    searchResultCount: json['search_result_count'] != null ? json['search_result_count'] as String : null,
    mouseOverThumbnails: json['mouse-over_thumbnails'] != null ? json['mouse-over_thumbnails'] as String : null,
    thumbnailSize: json['thumbnail_size'] != null ? json['thumbnail_size'] as String : null,
    thumbnailRows: json['thumbnail_rows'] != null ? json['thumbnail_rows'] as String : null,
    thumbnailScaling: json['thumbnail_Scaling'] != null ? json['thumbnail_Scaling'] as String : null,
    viewportOverride: json['viewport_override'] != null ? json['viewport_override'] as String : null,
    sortOrderComments: json['sort_order_comments'] != null ? json['sort_order_comments'] as String : null,
    showCommentVotes: json['show_comment_votes'] != null ? json['show_comment_votes'] as String : null,
    sortOrderTags: json['sort_order_tags'] != null ? json['sort_order_tags'] as String : null,
    showGalleryPageNumbers: json['show_gallery_page_numbers'] != null ? json['show_gallery_page_numbers'] as String : null,
    hentaiAtHomeLocalNetworkHost: json['hentaiAtHome_local_network_host'] != null ? json['hentaiAtHome_local_network_host'] as String : null,
    originalImages: json['original_images'] != null ? json['original_images'] as String : null,
    alwaysUseMpv: json['always_use_mpv'] != null ? json['always_use_mpv'] as String : null,
    mpvStyle: json['mpv_style'] != null ? json['mpv_style'] as String : null,
    mpvThumbnailPane: json['mpv_thumbnail_pane'] != null ? json['mpv_thumbnail_pane'] as String : null
  );
  
  Map<String, dynamic> toJson() => {
    'profilelist': profilelist.map((e) => e.toJson()).toList(),
    'profile_selected': profileSelected,
    'default_profile': defaultProfile,
    'load_image_through_hAtH': loadImageThroughHAtH,
    'load_browsing_country': loadBrowsingCountry,
    'image_size': imageSize,
    'image_size_horizontal': imageSizeHorizontal,
    'image_size_vertical': imageSizeVertical,
    'gallery_name_display': galleryNameDisplay,
    'archiver_settings': archiverSettings,
    'front_page_settings': frontPageSettings,
    'ct_doujinshi': ctDoujinshi,
    'ct_manga': ctManga,
    'ct_artistcg': ctArtistcg,
    'ct_gamecg': ctGamecg,
    'ct_western': ctWestern,
    'ct_non-h': ctNonH,
    'ct_imageset': ctImageset,
    'ct_cosplay': ctCosplay,
    'ct_asianporn': ctAsianporn,
    'ct_misc': ctMisc,
    'favorites0': favorites0,
    'favorites1': favorites1,
    'favorites2': favorites2,
    'favorites3': favorites3,
    'favorites4': favorites4,
    'favorites5': favorites5,
    'favorites6': favorites6,
    'favorites7': favorites7,
    'favorites8': favorites8,
    'favorites9': favorites9,
    'sort_order_favorites': sortOrderFavorites,
    'ratings': ratings,
    'xn': xn.map((e) => e.toJson()).toList(),
    'xl': xl.map((e) => e.toJson()).toList(),
    'xl_jpn_tl_1024': xlJpnTl1024,
    'xl_jpn_rw_2048': xlJpnRw2048,
    'xl_en_or_1': xlEnOr1,
    'xl_en_tr_1025': xlEnTr1025,
    'xl_en_re_2049': xlEnRe2049,
    'xl_chi_or_10': xlChiOr10,
    'xl_chi_tr_1034': xlChiTr1034,
    'xl_chi_re_2058': xlChiRe2058,
    'xl_dut_or_20': xlDutOr20,
    'xl_dut_tr_1044': xlDutTr1044,
    'xl_dut_re_2068': xlDutRe2068,
    'xl_fr_or_30': xlFrOr30,
    'xl_fr_tr_1054': xlFrTr1054,
    'xl_fr_re_2078': xlFrRe2078,
    'xl_gm_or_40': xlGmOr40,
    'xl_gm_tr_1064': xlGmTr1064,
    'xl_gm_re_2088': xlGmRe2088,
    'xl_hung_or_50': xlHungOr50,
    'xl_hung_tr_1074': xlHungTr1074,
    'xl_hung_re_2098': xlHungRe2098,
    'xl_ita_or_60': xlItaOr60,
    'xl_ita_tr_1084': xlItaTr1084,
    'xl_ita_re_2108': xlItaRe2108,
    'xl_kr_or_70': xlKrOr70,
    'xl_kr_tr_1094': xlKrTr1094,
    'xl_kr_re_2118': xlKrRe2118,
    'xl_poli_or_80': xlPoliOr80,
    'xl_poli_tr_1104': xlPoliTr1104,
    'xl_poli_re_2128': xlPoliRe2128,
    'xl_por_or_90': xlPorOr90,
    'xl_por_tr_1114': xlPorTr1114,
    'xl_por_re_2138': xlPorRe2138,
    'xl_ru_or_100': xlRuOr100,
    'xl_ru_tr_1124': xlRuTr1124,
    'xl_ru_re_2148': xlRuRe2148,
    'xl_spa_or_110': xlSpaOr110,
    'xl_spa_tr_1134': xlSpaTr1134,
    'xl_spa_re_2158': xlSpaRe2158,
    'xl_thai_or_120': xlThaiOr120,
    'xl_thai_tr_1144': xlThaiTr1144,
    'xl_thai_re_2168': xlThaiRe2168,
    'xl_vie_or_130': xlVieOr130,
    'xl_vie_tr_1154': xlVieTr1154,
    'xl_vie_re_2178': xlVieRe2178,
    'xl_na_or_254': xlNaOr254,
    'xl_na_tr_1278': xlNaTr1278,
    'xl_na_re_2302': xlNaRe2302,
    'xl_oth_or_255': xlOthOr255,
    'xl_oth_tr_1279': xlOthTr1279,
    'xl_oth_re_2303': xlOthRe2303,
    'tag_filtering_threshold': tagFilteringThreshold,
    'tag_watching_threshold': tagWatchingThreshold,
    'excluded_languages': excludedLanguages,
    'excluded_uploaders': excludedUploaders,
    'search_result_count': searchResultCount,
    'mouse-over_thumbnails': mouseOverThumbnails,
    'thumbnail_size': thumbnailSize,
    'thumbnail_rows': thumbnailRows,
    'thumbnail_Scaling': thumbnailScaling,
    'viewport_override': viewportOverride,
    'sort_order_comments': sortOrderComments,
    'show_comment_votes': showCommentVotes,
    'sort_order_tags': sortOrderTags,
    'show_gallery_page_numbers': showGalleryPageNumbers,
    'hentaiAtHome_local_network_host': hentaiAtHomeLocalNetworkHost,
    'original_images': originalImages,
    'always_use_mpv': alwaysUseMpv,
    'mpv_style': mpvStyle,
    'mpv_thumbnail_pane': mpvThumbnailPane
  };

  EhSettings clone() => EhSettings(
    profilelist: profilelist.map((e) => e.clone()).toList(),
    profileSelected: profileSelected,
    defaultProfile: defaultProfile,
    loadImageThroughHAtH: loadImageThroughHAtH,
    loadBrowsingCountry: loadBrowsingCountry,
    imageSize: imageSize,
    imageSizeHorizontal: imageSizeHorizontal,
    imageSizeVertical: imageSizeVertical,
    galleryNameDisplay: galleryNameDisplay,
    archiverSettings: archiverSettings,
    frontPageSettings: frontPageSettings,
    ctDoujinshi: ctDoujinshi,
    ctManga: ctManga,
    ctArtistcg: ctArtistcg,
    ctGamecg: ctGamecg,
    ctWestern: ctWestern,
    ctNonH: ctNonH,
    ctImageset: ctImageset,
    ctCosplay: ctCosplay,
    ctAsianporn: ctAsianporn,
    ctMisc: ctMisc,
    favorites0: favorites0,
    favorites1: favorites1,
    favorites2: favorites2,
    favorites3: favorites3,
    favorites4: favorites4,
    favorites5: favorites5,
    favorites6: favorites6,
    favorites7: favorites7,
    favorites8: favorites8,
    favorites9: favorites9,
    sortOrderFavorites: sortOrderFavorites,
    ratings: ratings,
    xn: xn.map((e) => e.clone()).toList(),
    xl: xl.map((e) => e.clone()).toList(),
    xlJpnTl1024: xlJpnTl1024,
    xlJpnRw2048: xlJpnRw2048,
    xlEnOr1: xlEnOr1,
    xlEnTr1025: xlEnTr1025,
    xlEnRe2049: xlEnRe2049,
    xlChiOr10: xlChiOr10,
    xlChiTr1034: xlChiTr1034,
    xlChiRe2058: xlChiRe2058,
    xlDutOr20: xlDutOr20,
    xlDutTr1044: xlDutTr1044,
    xlDutRe2068: xlDutRe2068,
    xlFrOr30: xlFrOr30,
    xlFrTr1054: xlFrTr1054,
    xlFrRe2078: xlFrRe2078,
    xlGmOr40: xlGmOr40,
    xlGmTr1064: xlGmTr1064,
    xlGmRe2088: xlGmRe2088,
    xlHungOr50: xlHungOr50,
    xlHungTr1074: xlHungTr1074,
    xlHungRe2098: xlHungRe2098,
    xlItaOr60: xlItaOr60,
    xlItaTr1084: xlItaTr1084,
    xlItaRe2108: xlItaRe2108,
    xlKrOr70: xlKrOr70,
    xlKrTr1094: xlKrTr1094,
    xlKrRe2118: xlKrRe2118,
    xlPoliOr80: xlPoliOr80,
    xlPoliTr1104: xlPoliTr1104,
    xlPoliRe2128: xlPoliRe2128,
    xlPorOr90: xlPorOr90,
    xlPorTr1114: xlPorTr1114,
    xlPorRe2138: xlPorRe2138,
    xlRuOr100: xlRuOr100,
    xlRuTr1124: xlRuTr1124,
    xlRuRe2148: xlRuRe2148,
    xlSpaOr110: xlSpaOr110,
    xlSpaTr1134: xlSpaTr1134,
    xlSpaRe2158: xlSpaRe2158,
    xlThaiOr120: xlThaiOr120,
    xlThaiTr1144: xlThaiTr1144,
    xlThaiRe2168: xlThaiRe2168,
    xlVieOr130: xlVieOr130,
    xlVieTr1154: xlVieTr1154,
    xlVieRe2178: xlVieRe2178,
    xlNaOr254: xlNaOr254,
    xlNaTr1278: xlNaTr1278,
    xlNaRe2302: xlNaRe2302,
    xlOthOr255: xlOthOr255,
    xlOthTr1279: xlOthTr1279,
    xlOthRe2303: xlOthRe2303,
    tagFilteringThreshold: tagFilteringThreshold,
    tagWatchingThreshold: tagWatchingThreshold,
    excludedLanguages: excludedLanguages,
    excludedUploaders: excludedUploaders,
    searchResultCount: searchResultCount,
    mouseOverThumbnails: mouseOverThumbnails,
    thumbnailSize: thumbnailSize,
    thumbnailRows: thumbnailRows,
    thumbnailScaling: thumbnailScaling,
    viewportOverride: viewportOverride,
    sortOrderComments: sortOrderComments,
    showCommentVotes: showCommentVotes,
    sortOrderTags: sortOrderTags,
    showGalleryPageNumbers: showGalleryPageNumbers,
    hentaiAtHomeLocalNetworkHost: hentaiAtHomeLocalNetworkHost,
    originalImages: originalImages,
    alwaysUseMpv: alwaysUseMpv,
    mpvStyle: mpvStyle,
    mpvThumbnailPane: mpvThumbnailPane
  );

    
  EhSettings copyWith({
    List<EhProfile>? profilelist,
    String? profileSelected,
    String? defaultProfile,
    String? loadImageThroughHAtH,
    String? loadBrowsingCountry,
    String? imageSize,
    String? imageSizeHorizontal,
    String? imageSizeVertical,
    String? galleryNameDisplay,
    String? archiverSettings,
    String? frontPageSettings,
    String? ctDoujinshi,
    String? ctManga,
    String? ctArtistcg,
    String? ctGamecg,
    String? ctWestern,
    String? ctNonH,
    String? ctImageset,
    String? ctCosplay,
    String? ctAsianporn,
    String? ctMisc,
    String? favorites0,
    String? favorites1,
    String? favorites2,
    String? favorites3,
    String? favorites4,
    String? favorites5,
    String? favorites6,
    String? favorites7,
    String? favorites8,
    String? favorites9,
    String? sortOrderFavorites,
    String? ratings,
    List<EhSettingItem>? xn,
    List<EhSettingItem>? xl,
    String? xlJpnTl1024,
    String? xlJpnRw2048,
    String? xlEnOr1,
    String? xlEnTr1025,
    String? xlEnRe2049,
    String? xlChiOr10,
    String? xlChiTr1034,
    String? xlChiRe2058,
    String? xlDutOr20,
    String? xlDutTr1044,
    String? xlDutRe2068,
    String? xlFrOr30,
    String? xlFrTr1054,
    String? xlFrRe2078,
    String? xlGmOr40,
    String? xlGmTr1064,
    String? xlGmRe2088,
    String? xlHungOr50,
    String? xlHungTr1074,
    String? xlHungRe2098,
    String? xlItaOr60,
    String? xlItaTr1084,
    String? xlItaRe2108,
    String? xlKrOr70,
    String? xlKrTr1094,
    String? xlKrRe2118,
    String? xlPoliOr80,
    String? xlPoliTr1104,
    String? xlPoliRe2128,
    String? xlPorOr90,
    String? xlPorTr1114,
    String? xlPorRe2138,
    String? xlRuOr100,
    String? xlRuTr1124,
    String? xlRuRe2148,
    String? xlSpaOr110,
    String? xlSpaTr1134,
    String? xlSpaRe2158,
    String? xlThaiOr120,
    String? xlThaiTr1144,
    String? xlThaiRe2168,
    String? xlVieOr130,
    String? xlVieTr1154,
    String? xlVieRe2178,
    String? xlNaOr254,
    String? xlNaTr1278,
    String? xlNaRe2302,
    String? xlOthOr255,
    String? xlOthTr1279,
    String? xlOthRe2303,
    String? tagFilteringThreshold,
    String? tagWatchingThreshold,
    String? excludedLanguages,
    String? excludedUploaders,
    String? searchResultCount,
    String? mouseOverThumbnails,
    String? thumbnailSize,
    String? thumbnailRows,
    String? thumbnailScaling,
    String? viewportOverride,
    String? sortOrderComments,
    String? showCommentVotes,
    String? sortOrderTags,
    String? showGalleryPageNumbers,
    String? hentaiAtHomeLocalNetworkHost,
    String? originalImages,
    String? alwaysUseMpv,
    String? mpvStyle,
    String? mpvThumbnailPane
  }) => EhSettings(
    profilelist: profilelist ?? this.profilelist,
    profileSelected: profileSelected ?? this.profileSelected,
    defaultProfile: defaultProfile ?? this.defaultProfile,
    loadImageThroughHAtH: loadImageThroughHAtH ?? this.loadImageThroughHAtH,
    loadBrowsingCountry: loadBrowsingCountry ?? this.loadBrowsingCountry,
    imageSize: imageSize ?? this.imageSize,
    imageSizeHorizontal: imageSizeHorizontal ?? this.imageSizeHorizontal,
    imageSizeVertical: imageSizeVertical ?? this.imageSizeVertical,
    galleryNameDisplay: galleryNameDisplay ?? this.galleryNameDisplay,
    archiverSettings: archiverSettings ?? this.archiverSettings,
    frontPageSettings: frontPageSettings ?? this.frontPageSettings,
    ctDoujinshi: ctDoujinshi ?? this.ctDoujinshi,
    ctManga: ctManga ?? this.ctManga,
    ctArtistcg: ctArtistcg ?? this.ctArtistcg,
    ctGamecg: ctGamecg ?? this.ctGamecg,
    ctWestern: ctWestern ?? this.ctWestern,
    ctNonH: ctNonH ?? this.ctNonH,
    ctImageset: ctImageset ?? this.ctImageset,
    ctCosplay: ctCosplay ?? this.ctCosplay,
    ctAsianporn: ctAsianporn ?? this.ctAsianporn,
    ctMisc: ctMisc ?? this.ctMisc,
    favorites0: favorites0 ?? this.favorites0,
    favorites1: favorites1 ?? this.favorites1,
    favorites2: favorites2 ?? this.favorites2,
    favorites3: favorites3 ?? this.favorites3,
    favorites4: favorites4 ?? this.favorites4,
    favorites5: favorites5 ?? this.favorites5,
    favorites6: favorites6 ?? this.favorites6,
    favorites7: favorites7 ?? this.favorites7,
    favorites8: favorites8 ?? this.favorites8,
    favorites9: favorites9 ?? this.favorites9,
    sortOrderFavorites: sortOrderFavorites ?? this.sortOrderFavorites,
    ratings: ratings ?? this.ratings,
    xn: xn ?? this.xn,
    xl: xl ?? this.xl,
    xlJpnTl1024: xlJpnTl1024 ?? this.xlJpnTl1024,
    xlJpnRw2048: xlJpnRw2048 ?? this.xlJpnRw2048,
    xlEnOr1: xlEnOr1 ?? this.xlEnOr1,
    xlEnTr1025: xlEnTr1025 ?? this.xlEnTr1025,
    xlEnRe2049: xlEnRe2049 ?? this.xlEnRe2049,
    xlChiOr10: xlChiOr10 ?? this.xlChiOr10,
    xlChiTr1034: xlChiTr1034 ?? this.xlChiTr1034,
    xlChiRe2058: xlChiRe2058 ?? this.xlChiRe2058,
    xlDutOr20: xlDutOr20 ?? this.xlDutOr20,
    xlDutTr1044: xlDutTr1044 ?? this.xlDutTr1044,
    xlDutRe2068: xlDutRe2068 ?? this.xlDutRe2068,
    xlFrOr30: xlFrOr30 ?? this.xlFrOr30,
    xlFrTr1054: xlFrTr1054 ?? this.xlFrTr1054,
    xlFrRe2078: xlFrRe2078 ?? this.xlFrRe2078,
    xlGmOr40: xlGmOr40 ?? this.xlGmOr40,
    xlGmTr1064: xlGmTr1064 ?? this.xlGmTr1064,
    xlGmRe2088: xlGmRe2088 ?? this.xlGmRe2088,
    xlHungOr50: xlHungOr50 ?? this.xlHungOr50,
    xlHungTr1074: xlHungTr1074 ?? this.xlHungTr1074,
    xlHungRe2098: xlHungRe2098 ?? this.xlHungRe2098,
    xlItaOr60: xlItaOr60 ?? this.xlItaOr60,
    xlItaTr1084: xlItaTr1084 ?? this.xlItaTr1084,
    xlItaRe2108: xlItaRe2108 ?? this.xlItaRe2108,
    xlKrOr70: xlKrOr70 ?? this.xlKrOr70,
    xlKrTr1094: xlKrTr1094 ?? this.xlKrTr1094,
    xlKrRe2118: xlKrRe2118 ?? this.xlKrRe2118,
    xlPoliOr80: xlPoliOr80 ?? this.xlPoliOr80,
    xlPoliTr1104: xlPoliTr1104 ?? this.xlPoliTr1104,
    xlPoliRe2128: xlPoliRe2128 ?? this.xlPoliRe2128,
    xlPorOr90: xlPorOr90 ?? this.xlPorOr90,
    xlPorTr1114: xlPorTr1114 ?? this.xlPorTr1114,
    xlPorRe2138: xlPorRe2138 ?? this.xlPorRe2138,
    xlRuOr100: xlRuOr100 ?? this.xlRuOr100,
    xlRuTr1124: xlRuTr1124 ?? this.xlRuTr1124,
    xlRuRe2148: xlRuRe2148 ?? this.xlRuRe2148,
    xlSpaOr110: xlSpaOr110 ?? this.xlSpaOr110,
    xlSpaTr1134: xlSpaTr1134 ?? this.xlSpaTr1134,
    xlSpaRe2158: xlSpaRe2158 ?? this.xlSpaRe2158,
    xlThaiOr120: xlThaiOr120 ?? this.xlThaiOr120,
    xlThaiTr1144: xlThaiTr1144 ?? this.xlThaiTr1144,
    xlThaiRe2168: xlThaiRe2168 ?? this.xlThaiRe2168,
    xlVieOr130: xlVieOr130 ?? this.xlVieOr130,
    xlVieTr1154: xlVieTr1154 ?? this.xlVieTr1154,
    xlVieRe2178: xlVieRe2178 ?? this.xlVieRe2178,
    xlNaOr254: xlNaOr254 ?? this.xlNaOr254,
    xlNaTr1278: xlNaTr1278 ?? this.xlNaTr1278,
    xlNaRe2302: xlNaRe2302 ?? this.xlNaRe2302,
    xlOthOr255: xlOthOr255 ?? this.xlOthOr255,
    xlOthTr1279: xlOthTr1279 ?? this.xlOthTr1279,
    xlOthRe2303: xlOthRe2303 ?? this.xlOthRe2303,
    tagFilteringThreshold: tagFilteringThreshold ?? this.tagFilteringThreshold,
    tagWatchingThreshold: tagWatchingThreshold ?? this.tagWatchingThreshold,
    excludedLanguages: excludedLanguages ?? this.excludedLanguages,
    excludedUploaders: excludedUploaders ?? this.excludedUploaders,
    searchResultCount: searchResultCount ?? this.searchResultCount,
    mouseOverThumbnails: mouseOverThumbnails ?? this.mouseOverThumbnails,
    thumbnailSize: thumbnailSize ?? this.thumbnailSize,
    thumbnailRows: thumbnailRows ?? this.thumbnailRows,
    thumbnailScaling: thumbnailScaling ?? this.thumbnailScaling,
    viewportOverride: viewportOverride ?? this.viewportOverride,
    sortOrderComments: sortOrderComments ?? this.sortOrderComments,
    showCommentVotes: showCommentVotes ?? this.showCommentVotes,
    sortOrderTags: sortOrderTags ?? this.sortOrderTags,
    showGalleryPageNumbers: showGalleryPageNumbers ?? this.showGalleryPageNumbers,
    hentaiAtHomeLocalNetworkHost: hentaiAtHomeLocalNetworkHost ?? this.hentaiAtHomeLocalNetworkHost,
    originalImages: originalImages ?? this.originalImages,
    alwaysUseMpv: alwaysUseMpv ?? this.alwaysUseMpv,
    mpvStyle: mpvStyle ?? this.mpvStyle,
    mpvThumbnailPane: mpvThumbnailPane ?? this.mpvThumbnailPane,
  );  

  @override
  bool operator ==(Object other) => identical(this, other) 
    || other is EhSettings && profilelist == other.profilelist && profileSelected == other.profileSelected && defaultProfile == other.defaultProfile && loadImageThroughHAtH == other.loadImageThroughHAtH && loadBrowsingCountry == other.loadBrowsingCountry && imageSize == other.imageSize && imageSizeHorizontal == other.imageSizeHorizontal && imageSizeVertical == other.imageSizeVertical && galleryNameDisplay == other.galleryNameDisplay && archiverSettings == other.archiverSettings && frontPageSettings == other.frontPageSettings && ctDoujinshi == other.ctDoujinshi && ctManga == other.ctManga && ctArtistcg == other.ctArtistcg && ctGamecg == other.ctGamecg && ctWestern == other.ctWestern && ctNonH == other.ctNonH && ctImageset == other.ctImageset && ctCosplay == other.ctCosplay && ctAsianporn == other.ctAsianporn && ctMisc == other.ctMisc && favorites0 == other.favorites0 && favorites1 == other.favorites1 && favorites2 == other.favorites2 && favorites3 == other.favorites3 && favorites4 == other.favorites4 && favorites5 == other.favorites5 && favorites6 == other.favorites6 && favorites7 == other.favorites7 && favorites8 == other.favorites8 && favorites9 == other.favorites9 && sortOrderFavorites == other.sortOrderFavorites && ratings == other.ratings && xn == other.xn && xl == other.xl && xlJpnTl1024 == other.xlJpnTl1024 && xlJpnRw2048 == other.xlJpnRw2048 && xlEnOr1 == other.xlEnOr1 && xlEnTr1025 == other.xlEnTr1025 && xlEnRe2049 == other.xlEnRe2049 && xlChiOr10 == other.xlChiOr10 && xlChiTr1034 == other.xlChiTr1034 && xlChiRe2058 == other.xlChiRe2058 && xlDutOr20 == other.xlDutOr20 && xlDutTr1044 == other.xlDutTr1044 && xlDutRe2068 == other.xlDutRe2068 && xlFrOr30 == other.xlFrOr30 && xlFrTr1054 == other.xlFrTr1054 && xlFrRe2078 == other.xlFrRe2078 && xlGmOr40 == other.xlGmOr40 && xlGmTr1064 == other.xlGmTr1064 && xlGmRe2088 == other.xlGmRe2088 && xlHungOr50 == other.xlHungOr50 && xlHungTr1074 == other.xlHungTr1074 && xlHungRe2098 == other.xlHungRe2098 && xlItaOr60 == other.xlItaOr60 && xlItaTr1084 == other.xlItaTr1084 && xlItaRe2108 == other.xlItaRe2108 && xlKrOr70 == other.xlKrOr70 && xlKrTr1094 == other.xlKrTr1094 && xlKrRe2118 == other.xlKrRe2118 && xlPoliOr80 == other.xlPoliOr80 && xlPoliTr1104 == other.xlPoliTr1104 && xlPoliRe2128 == other.xlPoliRe2128 && xlPorOr90 == other.xlPorOr90 && xlPorTr1114 == other.xlPorTr1114 && xlPorRe2138 == other.xlPorRe2138 && xlRuOr100 == other.xlRuOr100 && xlRuTr1124 == other.xlRuTr1124 && xlRuRe2148 == other.xlRuRe2148 && xlSpaOr110 == other.xlSpaOr110 && xlSpaTr1134 == other.xlSpaTr1134 && xlSpaRe2158 == other.xlSpaRe2158 && xlThaiOr120 == other.xlThaiOr120 && xlThaiTr1144 == other.xlThaiTr1144 && xlThaiRe2168 == other.xlThaiRe2168 && xlVieOr130 == other.xlVieOr130 && xlVieTr1154 == other.xlVieTr1154 && xlVieRe2178 == other.xlVieRe2178 && xlNaOr254 == other.xlNaOr254 && xlNaTr1278 == other.xlNaTr1278 && xlNaRe2302 == other.xlNaRe2302 && xlOthOr255 == other.xlOthOr255 && xlOthTr1279 == other.xlOthTr1279 && xlOthRe2303 == other.xlOthRe2303 && tagFilteringThreshold == other.tagFilteringThreshold && tagWatchingThreshold == other.tagWatchingThreshold && excludedLanguages == other.excludedLanguages && excludedUploaders == other.excludedUploaders && searchResultCount == other.searchResultCount && mouseOverThumbnails == other.mouseOverThumbnails && thumbnailSize == other.thumbnailSize && thumbnailRows == other.thumbnailRows && thumbnailScaling == other.thumbnailScaling && viewportOverride == other.viewportOverride && sortOrderComments == other.sortOrderComments && showCommentVotes == other.showCommentVotes && sortOrderTags == other.sortOrderTags && showGalleryPageNumbers == other.showGalleryPageNumbers && hentaiAtHomeLocalNetworkHost == other.hentaiAtHomeLocalNetworkHost && originalImages == other.originalImages && alwaysUseMpv == other.alwaysUseMpv && mpvStyle == other.mpvStyle && mpvThumbnailPane == other.mpvThumbnailPane;

  @override
  int get hashCode => profilelist.hashCode ^ profileSelected.hashCode ^ defaultProfile.hashCode ^ loadImageThroughHAtH.hashCode ^ loadBrowsingCountry.hashCode ^ imageSize.hashCode ^ imageSizeHorizontal.hashCode ^ imageSizeVertical.hashCode ^ galleryNameDisplay.hashCode ^ archiverSettings.hashCode ^ frontPageSettings.hashCode ^ ctDoujinshi.hashCode ^ ctManga.hashCode ^ ctArtistcg.hashCode ^ ctGamecg.hashCode ^ ctWestern.hashCode ^ ctNonH.hashCode ^ ctImageset.hashCode ^ ctCosplay.hashCode ^ ctAsianporn.hashCode ^ ctMisc.hashCode ^ favorites0.hashCode ^ favorites1.hashCode ^ favorites2.hashCode ^ favorites3.hashCode ^ favorites4.hashCode ^ favorites5.hashCode ^ favorites6.hashCode ^ favorites7.hashCode ^ favorites8.hashCode ^ favorites9.hashCode ^ sortOrderFavorites.hashCode ^ ratings.hashCode ^ xn.hashCode ^ xl.hashCode ^ xlJpnTl1024.hashCode ^ xlJpnRw2048.hashCode ^ xlEnOr1.hashCode ^ xlEnTr1025.hashCode ^ xlEnRe2049.hashCode ^ xlChiOr10.hashCode ^ xlChiTr1034.hashCode ^ xlChiRe2058.hashCode ^ xlDutOr20.hashCode ^ xlDutTr1044.hashCode ^ xlDutRe2068.hashCode ^ xlFrOr30.hashCode ^ xlFrTr1054.hashCode ^ xlFrRe2078.hashCode ^ xlGmOr40.hashCode ^ xlGmTr1064.hashCode ^ xlGmRe2088.hashCode ^ xlHungOr50.hashCode ^ xlHungTr1074.hashCode ^ xlHungRe2098.hashCode ^ xlItaOr60.hashCode ^ xlItaTr1084.hashCode ^ xlItaRe2108.hashCode ^ xlKrOr70.hashCode ^ xlKrTr1094.hashCode ^ xlKrRe2118.hashCode ^ xlPoliOr80.hashCode ^ xlPoliTr1104.hashCode ^ xlPoliRe2128.hashCode ^ xlPorOr90.hashCode ^ xlPorTr1114.hashCode ^ xlPorRe2138.hashCode ^ xlRuOr100.hashCode ^ xlRuTr1124.hashCode ^ xlRuRe2148.hashCode ^ xlSpaOr110.hashCode ^ xlSpaTr1134.hashCode ^ xlSpaRe2158.hashCode ^ xlThaiOr120.hashCode ^ xlThaiTr1144.hashCode ^ xlThaiRe2168.hashCode ^ xlVieOr130.hashCode ^ xlVieTr1154.hashCode ^ xlVieRe2178.hashCode ^ xlNaOr254.hashCode ^ xlNaTr1278.hashCode ^ xlNaRe2302.hashCode ^ xlOthOr255.hashCode ^ xlOthTr1279.hashCode ^ xlOthRe2303.hashCode ^ tagFilteringThreshold.hashCode ^ tagWatchingThreshold.hashCode ^ excludedLanguages.hashCode ^ excludedUploaders.hashCode ^ searchResultCount.hashCode ^ mouseOverThumbnails.hashCode ^ thumbnailSize.hashCode ^ thumbnailRows.hashCode ^ thumbnailScaling.hashCode ^ viewportOverride.hashCode ^ sortOrderComments.hashCode ^ showCommentVotes.hashCode ^ sortOrderTags.hashCode ^ showGalleryPageNumbers.hashCode ^ hentaiAtHomeLocalNetworkHost.hashCode ^ originalImages.hashCode ^ alwaysUseMpv.hashCode ^ mpvStyle.hashCode ^ mpvThumbnailPane.hashCode;
}
