name: Build mac

on:
  push:
    tags:
      - v*mac

jobs:
  build:
    name: Build mac
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Unlock secrets
        run: |
          brew install git-crypt
          echo $GIT_CRYPT_KEY | base64 -d -o grypt.key
          git-crypt unlock grypt.key
        env:
          GIT_CRYPT_KEY: ${{ secrets.ENCODED_GIT_CRYPT }}

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Build macos
        run: flutter build macos --release

      # 打包 dmg
      - name: Build dmg
        run: |
          APP_PATH=build/macos/Build/Products/Release/fehviewer.app
          APP_TEMP_DIR_PATH=build/macos/fehviewer
          mkdir $APP_TEMP_DIR_PATH
          cp -a $APP_PATH $APP_TEMP_DIR_PATH
          echo "hdiutil create -fs HFS+ -srcfolder $APP_TEMP_DIR_PATH -volname fehviewer build/macos/fehviewer.dmg"
          hdiutil create -fs HFS+ -srcfolder $APP_TEMP_DIR_PATH -volname fehviewer build/macos/fehviewer.dmg

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-mac
          path: |
            build/macos/*.dmg
            build/macos/Build/Products/Release/fehviewer.app