name: Build linux

on:
  push:
    tags:
      - v*linux

jobs:
  process:
    name: Build process
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.ENCODED_GIT_CRYPT }}


      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgtk-3-dev
          flutter config --enable-linux-desktop

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Linux
        run: flutter build linux --release

      - name: Generate tar.gz
        run: |
          APP_PATH=build/linux/fehviewer
          mkdir -p $APP_PATH
          cp -a build/linux/x64/release/bundle/* $APP_PATH
          cd build/linux && tar -zcvf FEhViewer_linux.tar.gz fehviewer

      - name: Create AppDir
        run: |
          cd scripts && ./build_appimage.sh


#      - name: list files
#        run: ls -R build/linux/x64/release/bundle

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-linux
          path: scripts/FEhViewer-x86_64.AppImage
