name: Build windows

on:
  push:
    tags:
      - v*win

jobs:
  build:
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Unlock secrets
        uses: a-morrison/windows-git-crypt-unlock@1.0.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.ENCODED_GIT_CRYPT }}

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "3.0.5"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build windows
        run: flutter build windows --release

      - name: Build App zip
        run: |
          $DestDir = "build\windows\FEhViewer"
          $SrcDir = "build\windows\runner\Release"
          New-Item -Path $DestDir -ItemType Directory
          Copy-Item $SrcDir\* -Recurse $DestDir
          Copy-Item -Filter *.dll -Path windows\* -Destination $DestDir -Force
          Compress-Archive $DestDir build\windows\FEhViewer.zip

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-windows
          path: build/windows/*.zip